### ISSUE TITLE
Migrate use of ImageDataGenerator to keras_cv

### ISSUE THREAD

**Issue by LukeWood** [udaylunawat/Whats-this-rock#1]
Hey there @udaylunawat!  Cool project you have going here!

I wanted to let you know that the Keras team has launched an extensive set of data augmentation layers in the new KerasCV repo: https://github.com/keras-team/keras-cv

I see you use ImageDataGenerator.  May I recommend substituting this with `RandAugment`, `CutMix`, and `MixUp`?  You can see how to do this here:

https://keras.io/guides/keras_cv/cut_mix_mix_up_and_rand_augment/

Thanks and let me know if you end up doing this!

**Comment by udaylunawat** [comment]
Hey @LukeWood! 

Thanks for introducing me to keras_cv!
I was literally just trying the cut_out augmentation yesterday!

I have followed through with the guide and tried implementing it!

You can take a look [here](https://colab.research.google.com/drive/1N1CIqdOKlJSJla5PU53Yn9KWSao47eMv).

I am facing an issue where in Google Colab where if I delete or move a corrupted image, it takes time for Colab to do the process, but before it's done, my DataFrame which contains the list of images is saved (which contains the corrupted files as well, which are already moved now).

Should I add a wait time after moving the files or is there any better way to deal with this!

Thank you again! Looking forward to playing around with keras_cv!

**Comment by udaylunawat** [comment]
Also I had to uninstall and reinstall keras and tensorflow to a nightly version.

```
%%bash
git clone https://github.com/keras-team/keras-cv.git
mv keras-cv/keras_cv /content/keras_cv

pip uninstall tensorflow -y
pip install tf-nightly==2.10.0.dev20220427

pip uninstall keras -y
pip install keras-nightly==2.10.0.dev2022042807```

And restart the kernel after this.
Is this behavior expected? Or am I doing something wrong here?

Also, please let me know if you can suggest some improvements for the project.

**Comment by udaylunawat** [comment]
![image](https://user-images.githubusercontent.com/24354945/171632442-f3b175c8-b6bb-4715-ba29-f10969bc3d0b.png)

Looks like I need to play around with different augmentations and figure out which one will be suitable for the dataset.

**Comment by LukeWood** [comment]
You should be able to use tensorflow==2.9.0

Does that fail for any reason?

**Comment by LukeWood** [comment]
> Also, please let me know if you can suggest some improvements for the project.

Typically, RandAugment, RandomFlip, RandomErasing, CutMix, MixUP,  IN THAT ORDER is a good augmentation scheme
